### ISSUE TITLE
Control colors

### ISSUE THREAD

**Issue by euharrison** [hn3000/loremicon#4]
Hi, nice project!

Do you plan to add any kind of color controls? Could be by querystring like https://loremicon.com/ngon/128/128/41878565/png?color[0]=cccccc&color[1]=777777

This is important to be closer to reality into mocks, that usually different color shine a lot 

Thanks in advanced

**Comment by hn3000** [comment]
Thanks, that's a great idea!

I would probably try to avoid the querystring -- encoding all parameters that determine the image in the URL was one of the design goals in this project. But I read your comment as "you wouldn't mind if it was in the querystring", am I right in assuming that you don't care either way? 

Without looking at the actualy feasibility, would a syntax like

/ngon/128/128/colors=ccc.777/41878565/png

work for you, too?

**Comment by euharrison** [comment]
Thanks for reply!

About the querystring, personally, it's doesn't matter if you use it or not. I believe most of the softwares and libs has a good way to work with encoding url, specialty the ones that download images from internet. But I think the querystring has more scalabilty and you can add infinite parameters as it doesn't matter the order of parameters.

If you need any help with it, I'm here :)

**Comment by euharrison** [comment]
For curiosity, here is a live example of how I'm using your tool

![Simulator Screen Shot - iPhone 11 - 2020-12-28 at 17 16 57](https://user-images.githubusercontent.com/557598/103291313-3537c180-49ca-11eb-994e-0f1775691ba8.png)

**Comment by hn3000** [comment]
Thanks for that bit of context!

**Comment by hn3000** [comment]
I implemented something, the README has some examples -- if this solves your problem, please close the issue!

**Comment by euharrison** [comment]
Thanks! This is really cool! Congrats! 🚀
